import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { BottomHeader, TopHeader } from "@/components/layout";
import { cn } from "@/lib/utils";
import ScrollToTopButton from "@/components/base/scroll-top-button";
import Footer from "@/components/layout/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Medical App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://kit.fontawesome.com/f685f4d055.js"
          crossOrigin="anonymous"
          async={true}
        />
        <link
          href="https://cdn.jsdelivr.net/npm/keen-slider@6.8.6/keen-slider.min.css"
          rel="stylesheet"
        />
        <link
          rel="shortcut icon"
          href="/images/logo.webp"
          type="image/x-icon"
        />
        <link
          href="https://db.onlinewebfonts.com/c/c4d8819fda4c3fd79e36cedcc8d422bb?family=Halyard+Display"
          rel="stylesheet"
        ></link>
      </head>
      <body
        className={cn(inter.className, "container p-0")}
        suppressHydrationWarning
      >
        <TopHeader />
        <BottomHeader />
        <main className="min-h-[79vh]">{children}</main>
        <ScrollToTopButton />
        <Footer />
      </body>
    </html>
  );
}
